# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["shingoyamazaki00+fastly@gmail.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-rust-default"
description = ""
language = "rust"
manifest_version = 3
name = "fastly-introduction-to-compute-rs"
service_id = "IKacyGh38kV7n7FVNYcheo"

[local_server]

[scripts]
  build = "cargo build --profile release"
