name: Deploy Application
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
          targets: wasm32-wasip1 # WebAssembly target

    - name: Deploy to Compute
      uses: fastly/compute-actions@v11
      env:
        FASTLY_API_TOKEN: ${{ secrets.FASTLY_API_TOKEN }}
